[font]
size = 11

[font.bold]
family = "JetBrains Mono NF"
style = "Bold"

[font.bold_italic]
family = "JetBrains Mono NF"
style = "Bold Italic"

[font.italic]
family = "JetBrains Mono NF"
style = "Italic"

[font.normal]
family = "JetBrains Mono NF"
style = "Regular"
